server:
    port: 8080
knife4j:
    enable: true
#    production: true
    # 开启Swagger的Basic认证功能,默认是false
    basic:
        enable: false
        # Basic认证用户名
        username: test
        # Basic认证密码
        password: 123
    documents:
        - group: 2.X版本
          name: 接口签名
          locations: classpath:markdown/*
    setting:
        language: zh-CN
        #是否显示界面中SwaggerModel功能
        enableSwaggerModels: true
        #是否显示界面中"文档管理"功能
        enableDocumentManage: true
        #重命名SwaggerModel名称,默认SwaggerModel
        swaggerModelName: 实体类列表
        #是否开启界面中对某接口的版本控制,如果开启，后端变化后Ui界面会存在小蓝点
        enableVersion: true
        #是否在每个Debug调试栏后显示刷新变量按钮,默认不显示
        enableReloadCacheParameter: false
        #调试Tab是否显示AfterScript功能,默认开启
        enableAfterScript: true
        #针对RequestMapping的接口请求类型,在不指定参数类型的情况下,如果不过滤,默认会显示7个类型的接口地址参数,如果开启此配置,默认展示一个Post类型的接口地址
        enableFilterMultipartApis: false
        #具体接口的过滤类型
        enableFilterMultipartApiMethodType: POST
        #请求参数缓存
        enableRequestCache: false
        enableHost: false
        enableHostText: 192.168.0.193:8000
        #自定义显示Home主页内容
        enableHomeCustom: false
        homeCustomLocation: classpath:markdown/home.md
        #禁用搜索框
        enableSearch: false
        #自定义底部Footer
        enableFooter: false
        enableFooterCustom: true
        footerCustomContent: Apache License 2.0 | Copyright  2021-[杭州施强教育科技有限公司]
        #是否开启动态参数调试功能
        enableDynamicParameter: true
        #允许调试
        enableDebug: true
        #禁用OpenApi结构显示
        enableOpenApi: false
        enableGroup: true
